### ISSUE TITLE
How to get API example working? 

### ISSUE THREAD

**Issue by funkytaco** [express-vue/express-vue-mvc-starter#13]
The following file's API endpoints don't seem to work.

https://raw.githubusercontent.com/express-vue/express-vue-mvc-starter/master/app/api.js

If I drop them in the routers directory, they work fine, but I'm thinking I'd rather separate the VC from the API routes and put them in that api.js file.

**Comment by danmademe** [comment]
i include this file in the router.js and then init it close to the top of the method.. somewhere before body parser, and the session stuff.. 

```js
const Api = require('./api');

//.......
//......

    //Api
    const api = Api.init();
    app.use('/api', api);
```

then any routes you put in there, will be outside of things like your session, or csrf protection .. 

remember if you want CSRF protection then you should be putting these in your internal controllers, not your external API
