### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by talalzaki** [express-vue/express-vue-mvc-starter#19]
what i must write in package.json us configuration i have no idea ?? thanks in advance

**Comment by danmademe** [comment]
Its JSON.

but what's your goal?

**Comment by talalzaki** [comment]
create web app uses sqlite3, vue-loader, eslint, and script for running webpack, thanks in advance.

**Comment by danmademe** [comment]
npm install

**Comment by danmademe** [comment]
Also this project does not use web pack, if you want that .. go use something else

**Comment by talalzaki** [comment]
so i can't use template.vue
